security:
  encoders:
    #Symfony\Component\Security\Core\User\User: 'auto'
    App\Entity\Admin:
      algorithm: bcrypt
    App\Entity\User:
      algorithm: bcrypt


  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: idPaneliste

    app_admin_provider:
      entity:
        class: App\Entity\User
        property: email


  firewalls:
    admin:
      anonymous: ~
      pattern:    ^/admin/
      provider: app_admin_provider
      form_login:
        login_path: app_admin_login
        check_path: app_admin_login
        default_target_path: admin_survey_tests
      logout:
        path:   app_admin_logout
        target: app_admin_login
      guard:
        authenticators:
           - App\Security\SecurityAdminAuthenticator
    main:
      anonymous: ~
      pattern:    ^/
      provider: app_user_provider
      form_login:
        login_path: app_login
        check_path: app_login
        default_target_path: user_accueil_index
      logout:
        path:   app_logout
        target: app_login
      guard:
        authenticators:
           - App\Security\SecurityAuthenticator

    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
    - { path: /admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY,  requires_channel: https }
    - { path: ^/admin/, roles: ROLE_ADMIN, requires_channel: https }
    #- { path: ^/admin/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #- { path: ^/inscription, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/paneliste, roles: ROLE_USER,  requires_channel: https}
    #- { path: ^/./, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https  }




