<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ4frfT6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ4frfT6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ4frfT6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ4frfT6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ4frfT6\App_KernelDevDebugContainer([
    'container.build_hash' => 'J4frfT6',
    'container.build_id' => '9e2c9ae7',
    'container.build_time' => 1596541873,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ4frfT6');
