<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ClubArticle extends \App\Entity\ClubArticle implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'id', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'item', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'title', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'testDate', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'location', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'locationBrand', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'category', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'product', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'comment', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'note', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'clubSubject', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'categoryHabit', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'headerHabit', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'habit', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'brand', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'user', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'visible', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'websearch', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'plane', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'waitingStatus', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'productName', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'productBrand', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'suggestion', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'satisfaction', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'satisfactionDetails'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'id', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'item', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'title', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'testDate', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'location', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'locationBrand', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'category', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'product', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'comment', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'note', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'clubSubject', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'categoryHabit', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'headerHabit', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'habit', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'brand', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'user', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'visible', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'websearch', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'plane', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'waitingStatus', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'productName', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'productBrand', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'suggestion', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'satisfaction', '' . "\0" . 'App\\Entity\\ClubArticle' . "\0" . 'satisfactionDetails'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ClubArticle $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTestDate($testDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTestDate', [$testDate]);

        return parent::setTestDate($testDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getTestDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTestDate', []);

        return parent::getTestDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocation($location)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocation', [$location]);

        return parent::setLocation($location);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocation', []);

        return parent::getLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory($category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', [$category]);

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', []);

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setProduct($product)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProduct', [$product]);

        return parent::setProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduct', []);

        return parent::getProduct();
    }

    /**
     * {@inheritDoc}
     */
    public function setComment($comment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComment', [$comment]);

        return parent::setComment($comment);
    }

    /**
     * {@inheritDoc}
     */
    public function getComment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComment', []);

        return parent::getComment();
    }

    /**
     * {@inheritDoc}
     */
    public function setNote($note)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNote', [$note]);

        return parent::setNote($note);
    }

    /**
     * {@inheritDoc}
     */
    public function getNote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNote', []);

        return parent::getNote();
    }

    /**
     * {@inheritDoc}
     */
    public function setClubSubject(\App\Entity\ClubSubject $clubSubject = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClubSubject', [$clubSubject]);

        return parent::setClubSubject($clubSubject);
    }

    /**
     * {@inheritDoc}
     */
    public function getClubSubject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClubSubject', []);

        return parent::getClubSubject();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\App\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisible($visible)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisible', [$visible]);

        return parent::setVisible($visible);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisible', []);

        return parent::getVisible();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocationBrand($locationBrand)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocationBrand', [$locationBrand]);

        return parent::setLocationBrand($locationBrand);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocationBrand()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocationBrand', []);

        return parent::getLocationBrand();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductName($productName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductName', [$productName]);

        return parent::setProductName($productName);
    }

    /**
     * {@inheritDoc}
     */
    public function setItem(\App\Entity\CategoryItem $item = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItem', [$item]);

        return parent::setItem($item);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductName', []);

        return parent::getProductName();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductBrand($productBrand)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductBrand', [$productBrand]);

        return parent::setProductBrand($productBrand);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductBrand()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductBrand', []);

        return parent::getProductBrand();
    }

    /**
     * {@inheritDoc}
     */
    public function getItem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItem', []);

        return parent::getItem();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebsearch($websearch)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebsearch', [$websearch]);

        return parent::setWebsearch($websearch);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebsearch()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebsearch', []);

        return parent::getWebsearch();
    }

    /**
     * {@inheritDoc}
     */
    public function setSatisfaction($satisfaction)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSatisfaction', [$satisfaction]);

        return parent::setSatisfaction($satisfaction);
    }

    /**
     * {@inheritDoc}
     */
    public function getSatisfaction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSatisfaction', []);

        return parent::getSatisfaction();
    }

    /**
     * {@inheritDoc}
     */
    public function setSatisfactionDetails($satisfactionDetails)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSatisfactionDetails', [$satisfactionDetails]);

        return parent::setSatisfactionDetails($satisfactionDetails);
    }

    /**
     * {@inheritDoc}
     */
    public function getSatisfactionDetails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSatisfactionDetails', []);

        return parent::getSatisfactionDetails();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlane($plane)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlane', [$plane]);

        return parent::setPlane($plane);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlane()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlane', []);

        return parent::getPlane();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoryHabit(\App\Entity\CategoryHabit $categoryHabit = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoryHabit', [$categoryHabit]);

        return parent::setCategoryHabit($categoryHabit);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoryHabit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoryHabit', []);

        return parent::getCategoryHabit();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeaderHabit(\App\Entity\HeaderHabit $headerHabit = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeaderHabit', [$headerHabit]);

        return parent::setHeaderHabit($headerHabit);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeaderHabit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeaderHabit', []);

        return parent::getHeaderHabit();
    }

    /**
     * {@inheritDoc}
     */
    public function setHabit(\App\Entity\Habit $habit = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHabit', [$habit]);

        return parent::setHabit($habit);
    }

    /**
     * {@inheritDoc}
     */
    public function getHabit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHabit', []);

        return parent::getHabit();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrand(\App\Entity\Brand $brand = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrand', [$brand]);

        return parent::setBrand($brand);
    }

    /**
     * {@inheritDoc}
     */
    public function getBrand()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrand', []);

        return parent::getBrand();
    }

    /**
     * {@inheritDoc}
     */
    public function setSuggestion($suggestion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuggestion', [$suggestion]);

        return parent::setSuggestion($suggestion);
    }

    /**
     * {@inheritDoc}
     */
    public function getSuggestion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSuggestion', []);

        return parent::getSuggestion();
    }

    /**
     * {@inheritDoc}
     */
    public function setWaitingStatus($waitingStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWaitingStatus', [$waitingStatus]);

        return parent::setWaitingStatus($waitingStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getWaitingStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWaitingStatus', []);

        return parent::getWaitingStatus();
    }

}
