<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Link extends \App\Entity\Link implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Link' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Link' . "\0" . 'numeroLien', '' . "\0" . 'App\\Entity\\Link' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Link' . "\0" . 'link', '' . "\0" . 'App\\Entity\\Link' . "\0" . 'dateUn', '' . "\0" . 'App\\Entity\\Link' . "\0" . 'token', '' . "\0" . 'App\\Entity\\Link' . "\0" . 'survey', '' . "\0" . 'App\\Entity\\Link' . "\0" . 'linkLogs', '' . "\0" . 'App\\Entity\\Link' . "\0" . 'type'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Link' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Link' . "\0" . 'numeroLien', '' . "\0" . 'App\\Entity\\Link' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Link' . "\0" . 'link', '' . "\0" . 'App\\Entity\\Link' . "\0" . 'dateUn', '' . "\0" . 'App\\Entity\\Link' . "\0" . 'token', '' . "\0" . 'App\\Entity\\Link' . "\0" . 'survey', '' . "\0" . 'App\\Entity\\Link' . "\0" . 'linkLogs', '' . "\0" . 'App\\Entity\\Link' . "\0" . 'type'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Link $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getNumeroLien()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroLien', []);

        return parent::getNumeroLien();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroLien(int $numeroLien)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroLien', [$numeroLien]);

        return parent::setNumeroLien($numeroLien);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateUn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateUn', []);

        return parent::getDateUn();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateUn($dateUn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateUn', [$dateUn]);

        return parent::setDateUn($dateUn);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLink($link)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLink', [$link]);

        return parent::setLink($link);
    }

    /**
     * {@inheritDoc}
     */
    public function getLink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLink', []);

        return parent::getLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setToken($token)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToken', [$token]);

        return parent::setToken($token);
    }

    /**
     * {@inheritDoc}
     */
    public function getToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToken', []);

        return parent::getToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setSurvey(\App\Entity\Survey $survey = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurvey', [$survey]);

        return parent::setSurvey($survey);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurvey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurvey', []);

        return parent::getSurvey();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function addLinkLog(\App\Entity\LinkLog $linkLog)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLinkLog', [$linkLog]);

        return parent::addLinkLog($linkLog);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLinkLog(\App\Entity\LinkLog $linkLog)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLinkLog', [$linkLog]);

        return parent::removeLinkLog($linkLog);
    }

    /**
     * {@inheritDoc}
     */
    public function getLinkLogs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLinkLogs', []);

        return parent::getLinkLogs();
    }

}
